# Generated by Django 5.2.1 on 2025-07-30 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
